language: generic 
sudo: required 
services:
    - docker

before_install:
    - docker build -t visionsoftau/react_test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true visionsoftau/react_test npm test -- --coverage

after_success:
    - docker build -t visionsoftau/multi-client ./client/
    - docker build -t visionsoftau/multi-nginx ./nginx/
    - docker build -t visionsoftau/multi-server ./server/
    - docker build -t visionsoftau/multi-worker ./worker/
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push visionsoftau/multi-client
    - docker push visionsoftau/multi-nginx
    - docker push visionsoftau/multi-server
    - docker push visionsoftau/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "muti-docker"
    env: "MutiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-200901989617"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY